on:
  schedule:
      - cron: "0 */4 * * *"
  workflow_dispatch:

name: post-skeet

permissions:
    contents: write

jobs:
  post-skeet:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BSKY_PAT: ${{ secrets.BSKY_TOKEN }}
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Set up R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          any::httr2
          any::rvest
          JBGruber/atrrr
          any::magick
          
    - name: Make post
      id: post
      run: |
        (Rscript valentine-bot.R 2>&1) | tee log
    
    - name: Log item
      if: success() || failure()
      run: |
        echo $(date -u +%FT%T.%3NZ),$(grep "Item URL" log | sed 's/Item URL: //g'),${{steps.post.conclusion}} >> post.log
        
    - name: Commit log
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add post.log
        git commit -m "[auto] Update bot post log $(TZ=America/New_York date +'%Y-%m-%d %H:%M')"
        git push
