on:
  schedule:
      - cron: "0 */4 * * *"
  workflow_dispatch:

name: post-skeet

jobs:
  post-skeet:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      BSKY_PAT: ${{ secrets.BSKY_TOKEN }}
    steps:

    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Set up R packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          any::httr2
          any::rvest
          JBGruber/atrrr
          any::magick
          
    - name: Make post
      run: |
        Rscript valentine-bot.R
